### ISSUE TITLE
2-column layout for ioslides?

### ISSUE THREAD

**Issue by andreashandel** [grantmcdermott/lecturenotes#1]
Hi Grant,
I was looking online for a way to do 2/multi-columns for ioslides presentations. I used to create 2 columns with 

<div style="float: left; width: 70%;">Text here</div> <div style="float: right; width: 30%;">Text here</div>

This works ok, but the problem is that if I try to add some single column text below the 2-column environment on the same slide, it still formats it as 2 column (not sure why).
I came across your solution and template, which works nicely and allows me to do a mix of 2- and 1-column layouts on the same slide. I also like the HTML+pdf output feature. I don't need that right now, but can see myself needing it in the future, so I've got your template bookmarked 😄. For now, I just took the CSS snippet from your preamble file. 

The one problem I have now however is that the width argument is ignored. It works fine in your html_document template, but for some reason using ioslides every column gets the same width, no matter what value i set the % to. Do you happen to have any experience/suggestion on how to get the width argument to work with ioslides? 
(Of course this is html output only since it's ioslides, not sure how this would be under beamer and i don't really use beamer). usually just html slides and then 'print to pdf' in the browser if i need a pdf version.)
Thanks!

**Comment by grantmcdermott** [comment]
Hi Andreas,

Sorry for the _super_ slow response. To add insult to injury, I'm afraid I don't know the answer to your question offhand. I haven't used ioslides for a long time. My guess is that they have some custom scaffolding underneath the hood that overrides the standard width argument (or, just as likely, redefines it as another parameter).

It's not quite the answer you're looking for, but I'm a huge fan of the [**xaringan**](https://github.com/yihui/xaringan) package / slide format. Somewhat ironically given our conversation, it doesn't use pandoc markdown. BUT it does offer excellent support for native multi-column environments. And is just incredibly flexible in general. Here's an example from my own lecture slides: [.Rmd](https://github.com/uo-ec607/lectures/blob/master/05-datatable/05-datatable.Rmd#L322-L353) and the resulting [.html](https://raw.githack.com/uo-ec607/lectures/master/05-datatable/05-datatable.html#31).

**Comment by andreashandel** [comment]
Thanks. I actually used xaringan for a while, but ended up dropping it because it wasn't using pandoc and thus led (among other things) to issues with bibtex referencing which made it hard to copy citations between slides and papers and lecture notes seamlessly. I wanted to like/use it since all the cool kids seem to use it these days :) but I just couldn't get it to fit well into my workflow.

**Comment by grantmcdermott** [comment]
Ha, fair enough.

I think I'll close this then. If you ever figure out a decent solution, please do leave a comment before. Cheers.
