### ISSUE TITLE
Why don't you configure this as "template"

### ISSUE THREAD

**Issue by larsvilhuber** [grantmcdermott/lecturenotes#3]
The button is at the top under Settings...

**Comment by grantmcdermott** [comment]
(Sorry Lars, I completely missed this...)

Sure, I can do that. I use templates for all my GitHub Classroom assignments. But I must ask: What will the particular benefit be here? (Wouldn't you still need to run through an R engine / IDE with full Rmd support (incl. pandoc etc)?)

**Comment by grantmcdermott** [comment]
Added to template. (Although I seem to have borked something in my recent pkgdown site, so I'll have to fix that when I get a chance.) Thanks again for the suggestion.
