### ISSUE TITLE
Broken links in http://grantmcdermott.com/lecturenotes/

### ISSUE THREAD

**Issue by eyayaw** [grantmcdermott/lecturenotes#4]
> You can view samples of the resulting output here:

>  1. [HTML](http://grantmcdermott.com/lecturenotes/docs/lecturenotes/lecturenotes.html)

> 2. [PDF](http://grantmcdermott.com/lecturenotes/docs/lecturenotes/lecturenotes.pdf)

**Comment by grantmcdermott** [comment]
Thanks @Eyayaw. Yeah, I know about those. Just need to find some time to figure out the optimal setup for the packagedown site. Will let you know when that's done.

**Comment by grantmcdermott** [comment]
Should be fixed now.
